name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run Tests + Coverage + HTML Report
        run: |
          pytest \
            --cov=. \
            --cov-report=xml \
            --html=test-report.html \
            --self-contained-html
      
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.html

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
      
      - name: Save Coverage Percentage
        run: |
          sudo apt-get update && sudo apt-get install -y libxml2-utils
          RAW=$(xmllint --xpath "string(/coverage/@line-rate)" coverage.xml)
          PERCENT=$(printf "%.0f" "$(echo "$RAW * 100" | bc -l)")
          
          echo "Coverage raw value: $RAW"
          echo "Coverage percent: $PERCENT%"
          
          echo "coverage=$PERCENT" >> $GITHUB_OUTPUT


      - name: Update coverage in Gist
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 27bfb7ba18da11fec73a66f189ac7ea3
        run: |
          COV=${{ steps.tests.outputs.coverage }}
          PERCENT=$(printf "%.0f" $(echo "$COVERAGE" | bc -l))
          
          echo "Coverage: $COV%"
          
          JSON=$(jq -n --arg cov "$PERCENT" '{"files": {"coverage.json": {"content": $cov}}}')
          
          curl -X PATCH \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$JSON" \
            "https://api.github.com/gists/$GIST_ID"




  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: tests   # Só roda se os testes passarem
    if: 
      github.ref == 'refs/heads/main' &&
      needs.tests.outputs.coverage >= 80 &&
      success()

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Health check
        run: |
          python - << 'EOF'
          import fastapi
          print("FastAPI OK ✅")
          EOF

      - name: Build Docker image
        run: docker build -t demo-app .
